---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь может удалить один или несколько товаров из корзины и продолжить выбор товаров в каталоге
  - На странице товара и в каталоге выводится название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность легко находить информацию о товарах, категориях, оплате и доставке
  - Пользователь должен иметь возможность оформить заказ и перейти на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя 
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина должна хранится в сессии браузера
implicit:
  - Сайт должен работать стабильно, без сбоев
  - Необходимо предусмотреть безопасные способы оплаты (платежныекарты, банковский перевод, электронные кошельки), чтобы удовлетворить потребности разных пользователей
  - Сайт должен соответствовать стандартам доступности, чтобы обеспечить удобство использования для людей с ограниченными возможностями
  - Сайт должен быть оптимизирован для поисковых систем, что включает в себя правильное использование метатегов, заголовков и других элементов SEO
  - Пользователь  должен иметь возможность обратиться в службу поддержки при помощи контактной информации через различные каналы (чат, телефон, электронная почта)
  - Пользователи должны иметь доступ к информации о вариантах доставки, стоимости и сроках
  - Обеспечить возможность пользователям оставлять отзывы и оценки товаров, чтобы помочь другим пользователям в их выборе
  - Описание товара русскоязычной версии интернет-магазина должно быть на русском языке
  - Пользователь должен получать уведомления о статусе заказа (подтверждение, отправка, доставка)
  - Пользователь должен иметь доступ к информации о интернет-магазине, включая его документацию, чтобы понимать условия использования, правила продажи, политику возврата товаров, возврата средств, гарантии, страховки и другие важные аспекты
  
